/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TestModel(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0_instance_0.geometry} material={materials.black} />
      <mesh geometry={nodes.mesh_0_instance_1.geometry} material={materials.black} rotation={[0, 0, Math.PI / 2]} />
      <mesh geometry={nodes.mesh_0_instance_2.geometry} material={materials.black} rotation={[0, -Math.PI / 2, 0]} />
      <lineSegments geometry={nodes.mesh_1.geometry} material={materials.black} />
    </group>
  )
}

useGLTF.preload('/model.glb')
